routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('admin');
});
Route::group(['prefix'=>'admin'],function (){




    //RUTAS AJAX

    Route::get('/ajax/obtenerFechaFinVacacion','VacacionController@obtenerFechaFinVacacion');


    //RUTAS TRABAJADORES

    Route::get('/trabajadores','TrabajadorController@index');
    Route::get('/trabajadores/create','TrabajadorController@create');
    Route::get('/trabajadores/create','TrabajadorController@create');
    Route::get('/trabajadores/filtrar','TrabajadorController@filtrar');
    Route::post('/trabajadores/cambiarestado','TrabajadorController@cambiarEstado');
    Route::post('/trabajadores/store','TrabajadorController@store');


    // vacaciones
    Route::get('/vervacaciones/{trabajador}','TrabajadorController@verVacaciones');


    //secciones
    Route::get('/secciones','SeccionController@index');
    Route::post('/secciones/store','SeccionController@store');
    Route::post('/secciones/update','SeccionController@update');
    Route::get('/secciones/destroy/{seccion}','SeccionController@destroy');

    //lugares
    Route::get('/lugares','LugarController@index');
    Route::post('/lugares/store','LugarController@store');
    Route::post('/lugares/update','LugarController@update');
    Route::get('/lugares/destroy/{lugar}','LugarController@destroy');

    //tipofuncionario
    Route::get('/tipofuncionario','TipoFuncionarioController@index');
    Route::post('/tipofuncionario/store','TipoFuncionarioController@store');
    Route::post('/tipofuncionario/update','TipoFuncionarioController@update');
    Route::get('/tipofuncionario/destroy/{tipo}','TipoFuncionarioController@destroy');

    //estado labarol
    Route::get('/estadolaboral','SeccionController@index');




});

app/Models/Trabajador.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Trabajador extends Model
{
protected $table='trabajadores';
    protected  $fillable=[
        'tipo_documento',
    'numero_documento',
    'nombres',
    'apellidos',
    'sexo',
    'fecha_nacimiento',
    'estado_civil',
    'profesion',
    'direccion',
    'nro_social',
    'estado_laboral',
    'telefono_fijo',
    'telefono_celular',
    'telefono_emergencia',
    'telefono_coorporativo',
    'nro_licencia',
    'cat_licencia',
    'fecha_fenecimiento',
    'email_personal',
    'email_profesional',
    'num_cuenta',
    'cuenta_banco',
        'tipo_funcionario',
        'estado_laboral',
        'item',
        'cargo',
        'sueldo',
        'seccion_id',
        'lugar_id',
        'antiguedad_ext',
        'fecha_ingreso',
        'tipo_funcionario',
        'nacionalidad',
        'fecha_inactividad',


    ];



    protected $dates=[
        'fecha_ingreso',
        'fecha_fenecimiento',
        'fecha_nacimiento'

    ];


    public function  historial_estados(){
        return $this->hasMany(HistorialCambio::class,'trabajador_id');
    }
    public function vinculos(){
        return $this->hasMany(Vinculo::class,'trabajadores_id');


    }

    public function lugar(){
      return $this->belongsTo(LugarModel::class,'lugar_id');
    }

    public function  setfechaIngresoAttribute($fecha){
    $this->attributes['fecha_ingreso']=Carbon::createFromFormat('d/m/Y',$fecha);
}
    public function  setfechaFenecimientoAttribute($fecha){
        $this->attributes['fecha_fenecimiento']=Carbon::createFromFormat('d/m/Y',$fecha);
    }
    public function  setfechaNacimientoAttribute($fecha){
        $this->attributes['fecha_nacimiento']=Carbon::createFromFormat('d/m/Y',$fecha);
    }

    public function seccion(){
        return $this->belongsTo(LugarModel::class,'seccion_id');

    }

    public   function scopeAntiguedad($anio){

    $anios_ext=explode('/',$this->antiguedad_ext)[0];
    $antiguedad =Carbon::now()->year;
    $anios=Carbon::now()->year -$this->fecha_ingreso->year;
         return $anios_ext+$anios;

   }

   public  function antiguedad_por_anio($anio){
       $anios_ext=explode('/',$this->antiguedad_ext)[0];
       $anios=$anio-$this->fecha_ingreso->year;
       return $anios_ext+$anios;

    }

   public function getnombreCompletoAttribute(){
       return $this->nombres.' '.$this->apellidos;
   }
}

resources/views/admin/trabajadores/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Trabajadores</h3>
            <div class="row">


            <a   href="{{url('admin/trabajadores/create')}}" class=" pull-left btn  btn-success"><i class="fa fa-plus"></i> Registrar nuevo trabajador </a>


                <div style="margin-top: -40px" class=" navbar-right col-md-2">

            <form action="{{url('/admin/trabajadores/filtrar')}}" method="get" class="form" id="form-filtrar">
                    {!!csrf_field()  !!}
                <div class="form-group">
                    <div class="col-md-12">
                    <label for="" class="control-label">Filtrar</label>
                    <select name="filtro" id="filtro" class="form-control">
                        <option value="" >SELECCIONAR</option>
                        <option value="ACTIVO" @if(isset($estado) && $estado=='ACTIVO') selected @endif>ACTIVOS</option>
                        <option value="INACTIVO" @if(isset($estado) && $estado=='INACTIVO') selected @endif>INACTIVOS</option>
                        <option value="TODOS" @if(isset($estado) && $estado=='TODOS') selected @endif>TODOS</option>
                    </select>
                    </div>
                </div>
            </form>
            </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="dataTable table" id="table">
                <thead>
                <tr class="titulos">

                    <th>Tipo Doc/Num Doc</th>
                    <th>Nombres</th>
                    <th>Sexo</th>
                    <th>Est.Civil</th>
                    <th>Fecha Nac.</th>
                    <th>Cargo</th>
                    <th>Ubicacion</th>
                    <th>Proyecto/Planta</th>
                    <th>Sueldo</th>
                    <th>Acciones</th>
                </tr>
                </thead>

                @if(count($trabajadores)>0)
                    @foreach($trabajadores as  $row)
                        <tr @if(isset($estado) && $estado=='TODOS')@if($row->estado_laboral=='INACTIVO') class="bg-danger" @endif @endif>

                            <td>{{$row->tipo_documento}}/{{$row->num_documento}}</td>
                            <td>{{$row->nombres}} {{$row->apellidos}}</td>
                            <td>{{$row->sexo}}</td>
                            <td>{{$row->estado_civil}}</td>
                            <td>{{$row->fecha_nacimiento}}</td>
                            <td>{{$row->cargo}}</td>
                            <td>

                                @if(isset($row->lugar->nombre))
                                    {{$row->lugar->nombre}}/
                                    @endif
                                    @if(isset($row->seccion->nombre))
                                        {{$row->seccion->nombre}}
                                    @endif
                                    </td>
                            <td></td>
                            <td>{{$row->sueldo}}</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-dark btn-xs"><i class="fa fa-gears"></i></button>
                                    <button type="button" class="btn btn-dark btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <span class="caret"></span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>

                                    @if($row->estado_laboral=='ACTIVO')
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">EDITAR</a>
                                        </li>
                                        <li>
                                            <a href="#myModal{{$row->id}}" data-toggle="modal">CAMBIAR INATIVO</a>
                                        </li>

                                        <li><a href="{{url('admin/vervacaciones')}}/{{$row->id}}">VER VACACIONES</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a>
                                        </li>
                                    </ul>
                                        @else
                                        <ul class="dropdown-menu" role="menu">

                                            <li>
                                                <a href="#myModal{{$row->id}}" data-toggle="modal">CAMBIAR ACTIVO</a>
                                            </li>


                                            {{--<li><a href="#">Separated link</a></li>--}}
                                        </ul>
                                        @endif


                                </div>
                                <div id="myModal{{$row->id}}" class="modal fade" role="dialog">
                                    <div class="modal-dialog ">

                                        <!-- Modal content-->
                                        <div class="modal-content ">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">CAMBIAR A ESTADO @if($row->estado_laboral=='ACTIVO')  INACTIVO @else ACTIVO  @endif</h4>
                                            </div>
                                            <form action="{{url('admin/trabajadores/cambiarestado')}}" method="post"  class="form-horizontal" id="form" >
                                                {!! csrf_field() !!}
                                                <input type="hidden"  name="id" value="{{$row->id}}">
                                                <input type="hidden"  name="estado" value="{{$row->estado_laboral}}">
                                                <div class="modal-body">

                                                    <div class="form-group">
                                                        <label for="" class="col-md-2">NOMBRES</label>
                                                        <div class="col-md-8">
                                                            <input type="text" value="{{$row->nombre_completo}}" readonly name="nombre" id="nombre" class="form-control">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-2">FECHA</label>
                                                        <div class="col-md-3">
                                                            <input type="text" name="fecha"  value="{{date('d/m/Y')}}" id="fecha" class="date-picker form-control">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                                    <button type="submit" class="btn btn-success" >Guardar</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>

                                {{--<a href="" class="btn btn-warning btm-xs"><i  class="fa fa-pencil"></i></a>--}}


                            </td>
                        </tr>

                    @endforeach
                    @endif

            </table>
        </div>


    </div>
    @stop
@section('myscript')
    <script>
        $(document).ready(function(){

          $('.dataTable').dataTable({});

            $('#filtro').change(function () {

               if($(this).val()!=''){
                   $('#form-filtrar').submit();
               }
            });
        });
    </script>
    @stop

resources/views/admin/trabajadores/vacaciones.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Vacaciones</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-6">
            <h4>NOMBRE:<strong>{{$trabajador->nombre_completo}}</strong></h4>
            <h4>CARGO :<strong>{{$trabajador->cargo}}</strong></h4>
            </div>
            <div class="col-md-6">
                <h4>F. INGRESO:<strong>{{$trabajador->fecha_ingreso->format('d/m/Y')}}</strong></h4>
                <h4>ANTIGUEDAD :<strong>{{$trabajador->antiguedad()}} AÑOS</strong></h4>
                </div>
            @if(count($datos))
                <table class="table dataTable">
                    <thead>
                    <tr>
                        <th>GESTION</th>
                        <th>ANTIGUEDAD <br>AÑOS</th>
                        <th>DIAS DE VACACIONES</th>
                        <th>FECHA INICIO</th>
                        <th>FECHA FIN</th>
                        <th>ESTADO</th>
                        <th>ACCIONES</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($datos as $r)
                        @php
                            $result=\App\Models\Vacacion::getVacacion($r['gestion'],$trabajador->id);
                        @endphp
                        <tr>
                            <td>{{$r['gestion']}}</td>
                            <td>{{$r['antiguedad']}}</td>
                            <td>{{$r['dias_vaca']}}</td>
                            <td></td>
                            <td></td>
                            <td>

                                @if(!$result && $r['gestion']!=date('Y'))
                                    <h6 class=" label label-danger">VACACION PERDIDA</h6>
                                    @endif
                            </td>
                            <td>
                                @if( $r['gestion']==date('Y'))


                                <a href="#myModal{{$r['gestion']}}"  data-toggle="modal" class="btn  btn-xs btn-success"><i class="fa fa-gear"></i> Generar</a>
                                <div id="myModal{{$r['gestion']}}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">REGISTRAR VACACION</h4>
                                            </div>
                                            <form action="{{url('admin/tipofuncionario/update')}}" method="post"  class="form-horizontal" id="form" >
                                                {!! csrf_field() !!}
                                                <input type="hidden"  name="id" >
                                                <div class="modal-body">

                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">FECHA REGISTRO</label>
                                                        <div class="col-md-3">
                                                            <input type="text" name="fecha_regsitro"  value="{{date('d/m/Y')}}" id="fecha_registro" class="date-picker form-control">
                                                        </div>

                                                    </div>
                                                    <div class="form-group">

                                                        @php
                                                            $vacacion=\App\Models\Vacacion::getVacacion($r['gestion']-1,$trabajador->id);

                                                             if($vacacion){
                                                             $dias=$vacacion->dias_total;
                                                             }
                                                              else{
                                                               $dias=0;
                                                              }
                                                        @endphp

                                                        <label for="" class=" col-md-3">DIAS ACUMULADOS
                                                        </label>
                                                        <div class="col-md-3">

                                                            <input type="text" name="dias_acumulados"  value="{{$dias}}" readonly id="dias_acumulados" class="date-picker form-control">
                                                        </div>

                                                                   @if($dias>0)
                                                        <label for="" class=" col-md-6">USAR DIAS ACUMULADOS
                                                            <input type="checkbox" id="cb_acum">
                                                        </label>
                                                                       @endif
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">DIAS ASIGNADOS</label>
                                                        <div class="col-md-3">
                                                            <input type="number" name="dias_asignados"  readonly value="{{$r['dias_vaca']}}" id="dias_asignados" class=" form-control">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">NUM DIAS PERMISO</label>
                                                        <div class="col-md-3">
                                                            <input type="number" name="dias_permiso" value="0"  id="dias_permiso" class=" form-control">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">NUM DIAS TOTAL</label>
                                                        <div class="col-md-3">
                                                            <input type="number" name="dias_total"  readonly id="dias_total" class=" form-control">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">FECHA INICIO</label>
                                                        <div class="col-md-3">
                                                            <input type="text" name="fecha_inicio"  value="{{date('d/m/Y')}}"  readonly id="fecha_inicio" class="date-picker form-control">
                                                        </div>
                                                        <label for="" class="col-md-2">FECHA FIN</label>
                                                        <div class="col-md-3">
                                                            <input  type="text"  readonly name="fecha_fin"  readonly id="fecha_fin" class=" form-control">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">FECHA REINICIO</label>
                                                        <div class="col-md-3">
                                                            <input type="text" name="fecha_reinicio" value="{{date('d/m/Y')}}"  readonly id="fecha_reinicio" class="date-picker form-control">
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="" class="col-md-3">OBSERVACIONES</label>
                                                        <div class="col-md-6">
                                                            <textarea name="observaciones" id="observaciones"  rows="3" class="form-control"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                                    <button type="submit" class="btn btn-success" >Guardar</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            @else
                <p>
                <h3 class="text-warning">No existen Vacaciones disponibles</h3>
                </p>
            @endif

        </div>


    </div>
@stop

@section('myscript')
    <script>
  function calular_fecha_fin(){
      var total=   $('#dias_total').val();
      var fi= $('#fecha_inicio').val();
      var url='/admin/ajax/obtenerFechaFinVacacion';
      $.ajax({
          url:url,
          method:'GET',
          data:{fecha_ini:fi,dias:total},
          dataType:'json',
          success:function(response){
              if(response.status){
                  $('#fecha_fin').val(response.fecha_fin);
              }

          },
          error:function(){}

      });
  }

        $(document).ready(function(){

            ///**** calculo de dias
            var dias_asig=parseInt($('#dias_asignados').val());
            var dias_per=parseInt($('#dias_permiso').val());
            calular_fecha_fin();

            $('#dias_total').val(dias_asig-dias_per);
            $('#cb_acum').click(function(){
                var dias_asig=parseInt($('#dias_asignados').val());
                var dias_acum=parseInt($('#dias_acumulados').val());
                var dias_per=parseInt($('#dias_permiso').val());
                if($(this).is(':checked')){
                    $('#dias_total').val(dias_asig+dias_acum-dias_per);
                }
                else {
                    $('#dias_total').val(dias_asig-dias_per);
                }
                calular_fecha_fin();
            });

            //////////////////////////////

            $('#fecha_inicio').change(function(){
                calular_fecha_fin();

            });

        });
    </script>
    @stop